### ISSUE TITLE
CREATE TABLE IF EXISTS Not handled properly by parser

### ISSUE THREAD

**Issue by jmlogan** [UBOdin/mimir#105]
The parser should handle the CREATE TABLE IF EXISTS construct. This is required when dealing with databases that do not reset when Mimir is restarted.

https://www.sqlite.org/lang_createtable.html

**Comment by mrb24** [comment]
support for CREATE TABLE IF NOT EXISTS was added in commit: f1c209fa4f7d3f88631afb6665957b88ca6d08ac. It needs to be merged into master.

**Comment by mrb24** [comment]
support for CREATE OR REPLACE TABLE was added in commit: eff436b7dc88214c2b1158a48252b8d4cf3d4522 . It needs to be merged into master.

**Comment by mrb24** [comment]
Merged into master by commit: de18c84e7c106dd2c0d832d785107c77471a7224
