### ISSUE TITLE
File import issues

### ISSUE THREAD

**Issue by willspoth** [UBOdin/mimir#106]
For future work:
- More intelligent importing of csv and other file types
- For example if columns in a csv don't match up, either throw an error or try and handle this case
- Column names that repeat, maybe adding some indexing
- Extension to other file types other then csv in the future

**Comment by willspoth** [comment]
ExtendedTypeInference branch now load csv will handle files that are larger than the header or have less/more commas in a row. It removes single quotes from the data set currently and later could be improved more, but was good enough to load in the ship data.

**Comment by okennedy** [comment]
Fixes merged in as part of #133
