### ISSUE TITLE
Schema Matching Lens

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#11]
Need to import this into the user-facing Scala codebase from Java land.

**Comment by CodingSage** [comment]
A basic implementation of this is done, but it's not working correctly. I didn't see this comment earlier, so I used edit distance and column type to just map the columns, this isn't giving correct results, it assigns the rating column to rating count for the example in the paper.
I couldn't find the Java code which has to be changed to Scala. Where can I find it?

**Comment by okennedy** [comment]
This sounds like a question for @sophieyoung717

**Comment by sophieyoung717** [comment]
Hi Vinayak,

The code is in my laptop in the office, I will send you more detail
tomorrow morning. The java code for schema matching is written by me and
tested. It should give you the correct probability for each mapping
candidate. Remember, it is just a rough estimation, so it is possible to
assign wrong candidate columns. But we want to remember the probability it
went wrong and later when user wants to improve the accuracy, we ask for
correct matching candidate.



best,
Ying.

**Comment by sophieyoung717** [comment]
Hi Vinayak,


Here is the code:
=======================
main()

HashMap<String,HashMap<String,Double>> sm_gcd=new HashMap<String,HashMap
<String,Double>>();

String matcherName="NGramDistance";//LevensteinDistance,JaroWinklerDistance,
NGramDistance can be used here.

String[] JCD={"Deposit_Amount","Numb_of_months","Purchase_item","Num
_of_years_in_company","Monthly_payment","married_gender","Age","job"};
 //target
schema

ArrayList<String[]> candidateJCD=new ArrayList<String[]>();

String[] s={"Payment_Status_Previous_Credit","Purpose","Sex_Marital_Status",
"Guarantors","Duration_in_Current_address","Most_valuable_available_asset",
"Concurrent_Credits","Type_of_apartment","Occupation","Telephone",
"Foreign_Worker"};//source or candidate schema

String[] d={"Account_Balance","Value_Savings_Stocks","Installment"};//source
or candidate schema

String[] in={"Duration_of_Credit_month","Credit_Amount",
"No_of_Credits_at_this_Bank","Length_of_current_employment",
"No_of_dependents"};//source or candidate schema

String[] age={"Age"};//source or candidate schema

//Above is my imitation of filter, filtering by type, d represents double,
in represents int, s string, age on range.

//follow the order of target schema.

candidateJCD.add(d);

candidateJCD.add(in);

candidateJCD.add(s);

candidateJCD.add(in);

candidateJCD.add(d);

candidateJCD.add(s);

candidateJCD.add(age);

 candidateJCD.add(s);


getMatchingMap(sm_gcd,matcherName,JCD,candidateJCD,12); //construct sm_gcd

=======================

public static void getMatchingMap(HashMap<String,HashMap<String,Double>>
result,String matcherName,String[] target,ArrayList<String[]> source,int
top){

for(int i=0;i<target.length;i++){

result.put(target[i],normalizeMapValue(getSchemaMatching(matcherName
,target[i],source.get(i),top)));

}

 }

=======================

public static HashMap<String,Double> normalizeMapValue(HashMap
<String,Double>input){

HashMap<String,Double> result=new HashMap<String,Double>();

double total=0.0;

for(double d:input.values()){

if(d!=0.0)

{total+=d;}

}

for(Entry<String,Double> entry:input.entrySet()){

result.put(entry.getKey(), (double)Math.round(entry.getValue
()/total*100)/100);

}

return result;

 }


=======================


public static HashMap<String,Double> getSchemaMatching(String
matcherName,String
target,String[] source,int top){

HashMap<String,Double> map = new HashMap<String,Double>();

ValueComparator bvc =  new ValueComparator(map);

StringDistance matcher=getMatcher(matcherName);

Map<String,Double> result_1=new TreeMap<String,Double>(bvc);

HashMap<String,Double> result=new HashMap<String,Double>();

 for(int i=0;i<source.length;i++){

map.put(source[i],(double) matcher.getDistance(target, source[i]));

}

result_1.putAll(map);//sort to obtain top some number values.

int counter=0;

for(Map.Entry<String, Double> entry:result_1.entrySet()){

if(counter<top){

result.put(entry.getKey(),entry.getValue());

counter++;

}

else break;

}

return result;

 }


=======================

public static StringDistance getMatcher(String criteria)

  {

    if ( criteria.equals("JaroWinklerDistance") )

      return new JaroWinklerDistance();

    else if ( criteria.equals("LevensteinDistance") )

      return new LevensteinDistance();

    else if ( criteria.equals("NGramDistance") )

      return new NGramDistance();



    return null;

   }


The jar file is lucene-spellchecker-3.6.1.jar , you can find it in
repository or search it online.



best,

Ying.

**Comment by CodingSage** [comment]
got it, thanks!

**Comment by CodingSage** [comment]
Ok, I have merged this code, and we are saving the probabilities of each columns mappings.
It still gives the same result as before because the only measure for similarity is the edit distance. Can't we use variance of the columns over some sample as measure to see similarity also? or a classification technique?

**Comment by okennedy** [comment]
Matching errors are ok.  The goal isn't to get a perfect match, the goal is to get a best guess.  This is fine for now.
