### ISSUE TITLE
Comment Lens

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#140]
It would be useful to have a lens that attaches comments to rows of data.  An initial use case is the CSV import feature, which may need to take corrective action on some rows of data like padding/trimming columns or recovering from format errors.

**Comment by mrb24** [comment]
Added in commit 249a352aa26d5c5647fe24b80a7f6895098c8bd9 needs to be merged into master

**Comment by mrb24** [comment]
commit c39044ccbff153f38bf38b7c96266914a2729f5e closes #140 
Comment Lens merged into master
