### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#16]
Sample(Expr) that produces a sample from one possible world of evaluating the expression.

**Comment by CodingSage** [comment]
This has been implemented. 
e.g ` SELECT SAMPLE(B) FROM SANE_R WHERE ROWID = 3; `
gives a sample for the required row. We can also pass in a seed value if we like
e.g ` SELECT SAMPLE(B, 1) FROM SANE_R WHERE ROWID = 3; `
In this I'm hashing the column name to an integer and adding the seed value to it, to generate a random value from the possible classes. If seed isn't being passed then I pass in the current time in milliseconds as the seed.
Please let me know if this is fine.

**Comment by okennedy** [comment]
Let's use nanoseconds. millis will get us in trouble at higher throughputs.

**Comment by CodingSage** [comment]
Ok, changed it to nanoseconds.

**Comment by okennedy** [comment]
You can use Var terms with an appropriate change to Eval.

**Comment by CodingSage** [comment]
Ok, Now I'm injecting seed values using bindings and passing Var("__SEED") terms

**Comment by okennedy** [comment]
Excellent!
