### ISSUE TITLE
out of order schema

### ISSUE THREAD

**Issue by willspoth** [UBOdin/mimir#164]
In SQLtoRA on line 530:

```
val newBindings = sch.map(
              (x) => (x._1, alias+"_"+x._1)
            ).toMap[String, String]
```

- scala .toMap returns a hashmap which doesn't preserve order. So newBindings loses the normal schema ordering that sch had before, this is where the problem is happening.
- I looked into changing it into a LinkedMap which would preserve the ordering but the compiler yelled at me so I don't know of a quick fix for this without changing a whole bunch of code so I figured I'd give you a chance to work some magic before I go changing everything and making a mess

**Comment by okennedy** [comment]
Fixed in 9c87eac55bd5715fcb2bcafda944afab1960160e
