### ISSUE TITLE
representation for schema matching result from data level to schema level

### ISSUE THREAD

**Issue by sophieyoung717** [UBOdin/mimir#165]
Current schema matching result on user interface marks all the data in red. It is a scaring. A more user-friendly way to present is to mark column names as red instead of data.

**Comment by okennedy** [comment]
This would probably need both back- and front-end changes.  

1. Separate data-dependent heuristics from data-independent heuristics in Percolator.percolateLite.  That is, right now percolateLite returns (Map[String->Expression], Expression) for Cell-, and Row-level nondeterminism respectively.  The first step would be making this return (Map[String->Boolean], Map[String->Expression], Boolean, Expression) for Column-, Cell-, Table-, and Row-level nondeterminism respectively.
    * A more "hacky" way to do this would be in Compiler, by running percolateLite twice... both before and after extracting VGTerms.
    * Another question is how Unions should be handled... since we might have highlighting that affects sets of rows (e.g., Results1 UNION ALL SchemaMatch(Results2)
2. Update Compiler to respect these changes.
3. Update ResultIterator and its implementations to respect these changes and have isColumnDeterministic and isTableDeterministic methods
4. Update the frontends to expose this metadata
    * `Database.dump`
    * The UI branch
5. Add the corresponding methods to CTExplainer
6. Update the frontends to trigger the appropriate methods.

**Comment by okennedy** [comment]
The more immediate issue here should be addressed with #193.  Adaptive schemas are one-level removed from attribute-level uncertainty, so this should keep every value from becoming red.

**Comment by okennedy** [comment]
Finishing #213 first should make implementing this far easier.

**Comment by mrb24** [comment]
closed by commit 0156f9ff02f1dd25d4ceaf790532218c0a65c4f1 and merged into master by commit 56338a66c45b48016379a28fd59d36193d205946
