### ISSUE TITLE
KeyRepair model explanations aren't showing the best guess properly

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#183]
KeyRepair model seems to pick the sequentially first option rather than the best guess when generating explanations.  This error doesn't seem to affect bestGuess(), just explanation()

**Comment by okennedy** [comment]
It's possible that this bug got fixed at some point in the last month.

**Comment by mrb24** [comment]
It appears that this bug is not with the KeyRepair lens but with the MissingValue lens.

**Comment by mrb24** [comment]
Fixed by commit: 8e48b5622da2fe792386c8a322257421c245515b
Merged into master by commit: de18c84e7c106dd2c0d832d785107c77471a7224
