### ISSUE TITLE
Proper serialization of queries in models

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#188]
A few models, notably KeyRepair and Weka, include the queries themselves in the model object.  These queries are not being properly serialized.  We should be using mimir.algebra.serialization to swap out VGTerms for SerializableVGTerms.

**Comment by okennedy** [comment]
In retrospect, the right thing to do here is to not be using VGTerms with model pointers.  This is going to require a substantial rewrite.

**Comment by okennedy** [comment]
Fixed in #229

**Comment by mrb24** [comment]
Oliver's MASSIVE cleanup strikes again and kills this issue.  Merged into master by commit: 5a3d0eb48f0d8eceae17adc3c7ff9041d4a5dba3
