### ISSUE TITLE
Port Mimir to Scala 1.11

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#205]
A lot of the scala world has migrated over to 1.11, and it's starting to get a bit difficult to avoid dependencies with year-old bugs.

**Comment by okennedy** [comment]
Addressed in #206 
This was easier than I remember it being the last time I tried it.

**Comment by mrb24** [comment]
commit c39044ccbff153f38bf38b7c96266914a2729f5e closes #205
2.11 branch merged into master
