### ISSUE TITLE
Seal Expression

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#219]
PrimitiveValue and Operator are both now sealed.  Expression should also be sealed, and we should do a full compile pass to make sure that there aren't any matcher warnings.

**Comment by okennedy** [comment]
Added in #229

**Comment by mrb24** [comment]
Expression sealed.  Merged into master by commit: 5a3d0eb48f0d8eceae17adc3c7ff9041d4a5dba3
Full compile pass reports no related match warnings.
