### ISSUE TITLE
Mimir Console not showing properly

### ISSUE THREAD

**Issue by anandsan1** [UBOdin/mimir#235]
The terminal is not running as expected.

The terminal doesn't show the user inputs once the MIMIR is executed.
![image](https://user-images.githubusercontent.com/29679762/27703489-8b51dbcc-5cd5-11e7-99db-e8faa214b0b0.png)

here the command (User input) "Analyze SELECT * FROM DS_test;" is not seen on the terminal
(I am using windows command prompt)

If a table under the Backend schema is dropped, the command "SELECT * FROM mimir_sys_tables;" (to list all the tables in current DB) won't work.
Commands:
1. SELECT * FROM mimir_sys_tables;
2. DROP TABLE DS_test_RAW;
3. SELECT * FROM mimir_sys_tables;
4. DROP TABLE DS_test;

Output:
Unable to drop tables under the schema Mimir.
![image](https://user-images.githubusercontent.com/29679762/27704028-2982ebc8-5cd7-11e7-8d3a-5253368c1b89.png)

These are the two issue that I found after doing a merge yesterday.

**Comment by okennedy** [comment]
I assume that you're doing a LOAD as well?

**Comment by anandsan1** [comment]
Yes, I did the load before this step.
