### ISSUE TITLE
Possible bug in SqlToRA and RAToSql conversions

### ISSUE THREAD

**Issue by Legacy25** [UBOdin/mimir#24]
I was playing around with some tables for CSV import + Type Inference when I noticed that with more than a few columns, the order of the columns of the tables are getting messed up. For example - 

![screenshot from 2015-07-22 20 45 11](https://cloud.githubusercontent.com/assets/5680571/8840716/13d94bc0-30b3-11e5-945b-1a92a215a2ff.png)

```Name``` is getting displayed in ```Married```, ```Married``` in ```Joining``` and ```Joining``` in ```Name```

This is because in line 219 of ```SqlToRA```, the ```toMap``` is returning a HashMap, which is not preserving the order of columns. Consequently, in RAToSql, the mappings of the ```SelectItem```s are wrong.

![screenshot from 2015-07-22 20 50 30](https://cloud.githubusercontent.com/assets/5680571/8840768/d8e22b26-30b3-11e5-924f-86420b34bc75.png)

![screenshot from 2015-07-22 20 56 04](https://cloud.githubusercontent.com/assets/5680571/8840806/50f6b92e-30b4-11e5-8584-8a2479d6bcdd.png)

```ret``` has incorrectly ordered mappings above.

Should we correct this?

**Comment by okennedy** [comment]
Yes.  Swapping the Map for a List( ( A, B ) ) seems reasonable.

**Comment by Legacy25** [comment]
Done.
