### ISSUE TITLE
Eval.applyCmp() not working as expected for TDate() types.

### ISSUE THREAD

**Issue by anandsan1** [UBOdin/mimir#259]
I am getting the error `'Error: Invalid Comparison $a $op $b' ` when trying to do Lessthan comparison between 2 date values
As much as I can understand, the reason for this error is that Eval.applyCmp() uses Typechecker.escalate() which returns TInterval() any any operations on (date, date). Here for comparison operations Typechecker.escalate() is expected to return TDate()

**Comment by okennedy** [comment]
This is turning out to be a bit more involved than I thought at first.  The Typechecker's escalation code needs to be broken up into several related, but distinct cases.  A solution is in progress.
