### ISSUE TITLE
PRAGMA LOG not working in production mode

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#274]
The runtime seems to link with a different Log4J logger in the assembly jar.  I'm not sure if this affects us with the independent jar files, but it means that it's impossible to change logging (runtime or otherwise).

**Comment by mrb24** [comment]
org.slf4j.slf4j-log4j12 is being included from the Spark dependency tree.  I Believe we can safely exclude it.

**Comment by mrb24** [comment]
closed by commit: 2db5b25f8e95e1583f0b897b631c34d327a8ae59
