### ISSUE TITLE
List Tables in web view

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#3]
A side-column with all tables and lenses would be helpful.  For example, see [W3School's Try SQL feature](http://www.w3schools.com/sql/trysql.asp?filename=trysql_select_all)

**Comment by Legacy25** [comment]
This has been implemented.

**Comment by okennedy** [comment]
One other request.  Could the lenses be listed as if they were normal tables?

**Comment by Legacy25** [comment]
Done!
