### ISSUE TITLE
Database.getVGTerms should retrieve row-specific VG Terms

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#32]
Consider the following expression:
```
CASE WHEN X IS NULL THEN {{foo}} ELSE X END
```

`ResultIterator.isDeterministic(...)` returns false for this expression only when X is in fact null.  getVGTerms should follow suit.  In fact, this may be better implemented as a method on resultIterator rather than on Database.  

The simple way to implement this would to use `Eval.inline()` to assign all of the `Column()` values and then emit the VGTerms remaining in the reduced expression.

**Comment by Legacy25** [comment]
Done, moved the getVGTerms call to a method in the ResultIterator interface, and changed the logic to add VGTerms from a CaseExpression only from the branch whose condition evaluates to true.
