### ISSUE TITLE
Drop or revise "Make Certain" feature for lens creation in MimirVizier

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#331]
Is there a compelling reason to keep this feature?  

As implemented, it kills ALL fine-grained provenance (by defining the newly created lens as an entirely new table). This kind of defeats the purpose of Mimir.  Proposed paths forward include:

- Drop "Make Certain" entirely.  
- Implement it Lens-side (i.e., lenses can register pre-acked models)
- Do a rewriting pass over the lens view, adding a "Ignore" field to VGTerms (DataWarnings can be outright removed).

My personal preference would be removing Make Certain.  @mrb24 : What do you think?

**Comment by mrb24** [comment]
dropped "Make Certain" completely. closed by commit: 5369d153bcbe57f0ac4e467f54e03128b2957636
