### ISSUE TITLE
Stratified Sampling Operator

### ISSUE THREAD

**Issue by mrb24** [UBOdin/mimir#362]
Add a sampling operator that supports stratified sampling.

see [this](https://github.com/apache/spark/blob/bbeb1911c8c8291cf8ebed85ecf6590d850616bd/sql/core/src/main/scala/org/apache/spark/sql/DataFrameStatFunctions.scala#L378) for the spark implementation

**Comment by okennedy** [comment]
Taking this on, since it's going to be needed for Atri's class.

**Comment by okennedy** [comment]
Implemented and waiting on #368 and a nice UX.  Working on that one next.

**Comment by okennedy** [comment]
Implementation merged
