### ISSUE TITLE
File import through Web interface

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#4]
A CSV file import feature would be helpful, and could form the basis for some later features for log parsing.

The semantics I'd be looking to see are something along the lines of:
```
SELECT * INTO new_table FROM uploaded_csv_file
```

**Comment by Legacy25** [comment]
A drag and drop mechanism for uploading csv files has been implemented.

**Comment by Legacy25** [comment]
There were a few issues with this, many of which have been hopefully sorted, need to run the server as superuser though for the upload to work correctly.

Has been tested on the awesomedb database. Drag dropping the ```awesomeness.csv``` into the upload box updates awesomedb correctly.

**Comment by okennedy** [comment]
Why the superuser requirement?

**Comment by Legacy25** [comment]
This error message was already there, this was a little broken because of the ```database is locked``` bugfix, but it has been fixed now. I have modified the error message to something more concise now though.
