### ISSUE TITLE
Improve feedback for type inference lens

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#43]
e.g., "'Guessed type 'type' for attribute 'attribute'"

and...

"Could not coerce 'string value' to 'type'"

**Comment by okennedy** [comment]
It may make sense to have this model create two separate VG terms: a type guess and another representing the coerced value.

**Comment by Legacy25** [comment]
I have separated the inference and casting into two separate models. The expression is now of the form:

```PROJECT attr => CASE WHEN {{ TypeCastModelVGTerm [ Var('ROWID'), {{ TypeInferenceModel [] }} ] }} IS NOT NULL THEN VGTerm ELSE attr```

Here is an explain - 
![screenshot from 2015-08-06 15 55 53](https://cloud.githubusercontent.com/assets/5680571/9121995/2d2eb1a8-3c54-11e5-99eb-da4fc592e6b2.png)

I have changed the ```CTAnalyzer.compileDeterministic``` a bit to make sure that values which are not cast show up as deterministic values, as can be seen here -

![screenshot from 2015-08-06 15 55 25](https://cloud.githubusercontent.com/assets/5680571/9122078/82c007e8-3c54-11e5-97f9-9991a02d45c9.png)

I am not sure that this is the required behavior though. There are two other options as far as I can see:

1. Keep the values that cannot be cast as NULL
2. Do best guess coercion on a case by case basis

But after our discussions last week I think the coercion should be part of another lens maybe...?

**Comment by Legacy25** [comment]
In this form now TYPE_INFERENCE cannot be composed with MISSING_VALUE, but it seems pretty trivial to combine MISSING_VALUE and TYPE_INFERENCE <b>MODELS</b> into a lens (DOMAIN_REPAIR?) and another lens that can combine the inference model with the casting model (with best-guess coercion)?

**Comment by okennedy** [comment]
Looks good.

**Comment by okennedy** [comment]
Mmm... no, at this stage, it probably makes sense to keep the output as 'NULL'.  

Instead, is it possible to embed the answer into the "reasons" column?  e.g., I cast 'A3' from a string to an integer.

**Comment by Legacy25** [comment]
Yes, should be possible... Will do that then...

**Comment by Legacy25** [comment]
Done!

**Comment by Legacy25** [comment]
I think passing a VGTerm as an argument to another VGTerm is breaking the parser. The type inference lens works fine but when I try to compose a missing value lens on top of it, it breaks. Is this something that can be handled or should I try to look for another approach that avoids this issue?
