### ISSUE TITLE
Highlight uncertain query attributes in web view

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#5]
Asterisks are good for text-only views. In a web interface, we should have highlighted cells instead.

**Comment by Legacy25** [comment]
This has been implemented, the look can be customized as required by simple CSS code, to whatever looks best.

**Comment by okennedy** [comment]
Great!  Is it possible to customize row-level and attribute-level uncertainty separately?  Right now, there's no way to distinguish between the two.  Perhaps adding a [border around](http://stackoverflow.com/questions/670424/border-around-specific-rows-in-a-table) uncertain &lt;tr&gt;s.

**Comment by Legacy25** [comment]
Yes, uncertain rows have the css class ```non_deterministic_row``` while uncertain cells have the css class ```non_deterministic_cell```

Currently, I am not yet sure how to style these but that will be a minor amount of css code based on a bit of experimentation and figuring out what looks most contrasting and in tune with the bootstrap theme. The background color and the text color alpha property can also be used to indicate the level of uncertainty down the road.

**Comment by okennedy** [comment]
A few minor tweaks in mimir@be56a41 and this seems good for now.
