### ISSUE TITLE
When mousing over a 'Reason' in the web view, highlight the originating lens in the lens view

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#53]
Low-prioriity issue.  Implement if easy to do so.

**Comment by CodingSage** [comment]
For now, all graph nodes with the same lens type get highlighted on hovering over the reason, i.e if there are 2 missing value nodes then both will get highlighted on hovering over a missing value reason. To highlight a specific node the reason will need to return the lens name. I'll look into that now.
