### ISSUE TITLE
CREATE LENS fails after SELECT

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#6]
Running any SELECT query and following it with a CREATE LENS:
```
SELECT * FROM sane_r;
CREATE LENS insane_r AS SELECT * FROM r WITH missing_value('C')
```
results in the following exception
```
java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:890)
	at org.sqlite.core.DB.newSQLException(DB.java:901)
	at org.sqlite.core.DB.execute(DB.java:807)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:50)
	at mimir.sql.JDBCBackend.update(JDBCBackend.scala:56)
	at mimir.Database.update(Database.scala:96)
	at mimir.lenses.LensManager.save(LensManager.scala:71)
	at mimir.lenses.LensManager.create(LensManager.scala:67)
```

**Comment by Legacy25** [comment]
This bug arises differently for brand new databases. The first create lens statement succeeds. The second gives the same error. I will work on this further.

**Comment by Legacy25** [comment]
This seems to be a bug with the ```closeOnCompletion()``` support of MySQL at class JDBCBackend

```
def execute(sel: String): ResultSet = 
  {
    // println(sel)
    val stmt = conn.createStatement();
    val ret = stmt.executeQuery(sel)
    stmt.closeOnCompletion();
    temp = stmt
    return ret;
  }
```

Even though I am closing the iterator in the WebAPI class, it doesn't seem to close the connection, which it should according to the documentation. I have implemented an ugly hack to get around this problem, by adding a dummy method to the Backend abstract class which returns to me the ```Statement``` variable, on which I'm calling exit manually after closing the iterator. This fixes the issue. 

Should I commit a cleaner more documented version of this approach, or think of a more elegant way?

**Comment by okennedy** [comment]
It seems like this might actually be WAI, and not a bug: See [Connection.commit()](http://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#commit()).  Bah.

Perhaps the simplest, cleanest fix here would be to add another layer of encapsulation and have Backend return a mimir.exec.ResultIterator rather than a java.sql.ResultSet.  ResultSet only makes appearances in mimir.Database, where it's immediately wrapped in a ResultSetIterator, so this should be a fairly minor change.

Then java.sql.Statement could be added as a second parameter to mimir.exec.ResultSetIterator, for ResultSetIterator.close().

**Comment by Legacy25** [comment]
That approach created quite a lot of problems, and broke the command line interface too. 

The root of the problem seems to be that every handler for a request to the server is its own thread, and I was using the same WebAPI instance for all of the methods. What I have gone with is having a new instance of the WebAPI class be generated for each request, and I have added a ```close()``` method to ```Backend``` which explicitly closes the connection after every request is processed. This seems to have fixed the issue.

**Comment by okennedy** [comment]
I see... so now there's one Connection instance per thread?  That's a bit ugly, but probably ok.
