### ISSUE TITLE
estimate value is 3, while other values in the column are strings.

### ISSUE THREAD

**Issue by sophieyoung717** [UBOdin/mimir#60]
<img width="757" alt="09b12b00-7782-4a28-bdec-7fae475f508c" src="https://cloud.githubusercontent.com/assets/9054304/9388583/6ef10420-4734-11e5-954e-4ba5433567c3.png">
CREATE LENS SaneProduct AS SELECT * FROM PRODUCT WITH MISSING_VALUE('CATEGORY');
SELECT * FROM SaneProduct;

**Comment by Legacy25** [comment]
Fixed
