### ISSUE TITLE
error on parsing the statement

### ISSUE THREAD

**Issue by sophieyoung717** [UBOdin/mimir#61]
try1: SELECT SaneProduct.pid, SaneProduct.category, allRatings.rating, allRatings.review_ct  
FROM (SELECT \* FROM saneRatings UNION SELECT \* FROM Ratings1) allRatings,SaneProduct
WHERE allRatings.pid= SaneProduct.id and SaneProduct.category IN ('phone','TV') OR allRatings.rating > 4

saneRatings: a schema matching lens on Ratings2 with ratings1typed schema as target schema 

ERROR: Unhandled Feature: Expression[Unknown]: SaneProduct.category IN ('phone', 'TV')

try2: SELECT SaneProduct.pid, SaneProduct.category, allRatings.rating, allRatings.review_ct  
FROM (SELECT \* FROM saneRatings UNION SELECT \* FROM Ratings1) allRatings,SaneProduct
WHERE allRatings.pid= SaneProduct.id and SaneProduct.category = 'phone' OR allRatings.rating > 4

ERROR: Type Mismatch [Numeric]: found TString, but expected TFloat

**Comment by okennedy** [comment]
`A IN (x, y, ...)` is SQL Syntactic sugar for: `A = x OR A = y OR A = z`

This should be a simple fix.  It only needs to be added to `SQLToRA. convert(Expression)`
