### ISSUE TITLE
Backend can't seem to distinguish between lens columns and underlying table columns

### ISSUE THREAD

**Issue by Legacy25** [UBOdin/mimir#62]
```sql
SELECT r.a, r.b, r.c, s.b, s.d from sane_r, s where r.b = s.b;
```

I'm guessing this is supposed to throw an error because we are trying to project attributes of ```r``` when joining ```sane_r```, but it doesn't. Need to put in some checks in percolate?

**Comment by okennedy** [comment]
This seems like a SqlToRA bug.  I'll write a typechecker tomorrow that should fix this.
