### ISSUE TITLE
Confidence values for row-level uncertainty

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#7]
Provide a way to compute the probability of a row being in the output set.  That is, the chance that __MIMIR_CONDITION evaluates to BooleanPrimitive(true)

**Comment by CodingSage** [comment]
Basic implementation for this has been done. I'm not sure about how the interface should have been for this. I am calling the function PROB for now, we can change that.
Right now if we run a query like `SELECT PROB() FROM SANE_R WHERE B = 2; `
We get the following result 
```
+-------------+-------------+
|       ROWID | EXPR_1_PROB |
+-------------+-------------+
|         '1' |      '100%' |
|         '3' |       '47%' (This row may be invalid) |
|         '4' |      '100%' |
|         '6' |      '100%' |
|         '7' |      '100%' |
+-------------+-------------+
```
For knowing the probability of a row being present we need to mention the uncertain columns in the where clause. So, if I have 2 lens's one over 'B' and one over 'C'. The query would be something like
`SELECT PROB() FROM SANE_R, INSANE_R WHERE SANE_R.B = 2 AND INSANE_R.C = 1; `
Is this fine?

**Comment by okennedy** [comment]
Let's look at that
```
SELECT PROB() FROM SANE_R, INSANE_R WHERE SANE_R.B = 2
```
If there's no `insane_r.c = 1` predicate, then the value of `insane_r.c` does not matter.  The result doesn't change, regardless of what value I assign to insane_r.c, both in terms of values and in terms of which rows are in the result set.

Even if I were to run a query like:
```
SELECT insane_r.c, PROB() FROM SANE_R, INSANE_R WHERE SANE_R.B = 2
```
... then `c` contributes only to a single value column.  The probability of the row being present stays the same.

This looks good.  Feel free to close the ticket after the code review.
