### ISSUE TITLE
Add driver-specific pre-processing to SQL before evaluation

### ISSUE THREAD

**Issue by Legacy25** [UBOdin/mimir#76]
Handle quirks of each backend, including strong vs weak typing issues, variations in syntax and data types, etc.

**Comment by Legacy25** [comment]
Example - Dates in SQLite and Oracle are specified differently, translations to and from Mimir RA have to be driver specific, right now this is done on a case by case basis in SqlToRA and RAToSql, this code should be abstracted out if there more cases arise, possibly have driver specific SqlToRA and RAToSql modules.

**Comment by okennedy** [comment]
Implemented in Backend.scala in #93.
