### ISSUE TITLE
Variance values for cell-level uncertainty.

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#8]

**Comment by CodingSage** [comment]
Basic implementation of this is done. I need to test it further. Right now it works as follows,
SELECT VAR(B) FROM SANE_R;
gives the following result

+-------------+
|  EXPR_1_VAR |
+-------------+
|           0 |
|           0 |
|8.96187201351742 |
|           0 |
|           0 |
|           0 |
|           0 |
+-------------+

**Comment by okennedy** [comment]
8.96 seems ... a bit high.  If memory serves, SANE_R's B attribute can only take values from 1-5.  A 9 shouldn't even be possible, even with an even split of samples with B=1 and B= 5.

**Comment by okennedy** [comment]
Just tested it out.  The numbers seem a bit more sane.  We should do a code review, but otherwise looks good.  Let's integrate it into the UI

**Comment by CodingSage** [comment]
I had made a mistake with the indexes in the earlier one. But the variance calculation is still wrong. When I get classes from the classifiers getVotesForInstance method, I thought that we get the PDF for the model, but the probabilities don't add up to one. I'm not sure if I have understood something wrong here.

**Comment by CodingSage** [comment]
Ok, the returned values were probabilities which the classifiers belonging to each class assign for the given instance. It is not the PDF.
There was a function for variance in the moa Instances class, which when used with the class index returned the required attributes variance. The variance seems to be working correctly now.

**Comment by okennedy** [comment]
Yeah, the only lens we have at the moment is a categorical version of the DCR lens.  Realistically, this is not something for which variance will be particularly helpful.  We probably need a few more lenses before we can test this process end-to-end rather than with just unit test cases.

**Comment by CodingSage** [comment]
Variance is now calculated by sampling.

**Comment by okennedy** [comment]
Cool!  Close the ticket after the code review.
