### ISSUE TITLE
Tables list doesn't update after file upload

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir#88]

**Comment by michaelkulbacki** [comment]
Was this functionality working on master, but then on my branch with my changes it stopped working?

**Comment by okennedy** [comment]
Yes. Only caught it just yesterday 

-O

**Comment by michaelkulbacki** [comment]
Ill compare it to master and see if I changed something

**Comment by michaelkulbacki** [comment]
Browser caching issues wouldn't allow me to see the updated table, issue is fixed
